package com.sarige.tmall.mapper;

import com.sarige.tmall.pojo.PropertyValue;
import com.sarige.tmall.util.example.PropertyValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PropertyValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated
     */
    long countByExample(PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated
     */
    int deleteByExample(PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated
     */
    int insert(PropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated
     */
    int insertSelective(PropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated
     */
    List<PropertyValue> selectByExample(PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated
     */
    PropertyValue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PropertyValue record, @Param("example") PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PropertyValue record, @Param("example") PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PropertyValue record);
}